In [34]:
import pandas as pd

df = pd.read_csv('../Dataset/fake_news_dataset.csv')
df.head()

,title,text,date,source,author,category,label
0,Foreign Democrat final.,more tax development both store agreement lawy...,2023-03-10,NY Times,Paula George,Politics,real
1,To offer down resource great point.,probably guess western behind likely next inve...,2022-05-25,Fox News,Joseph Hill,Politics,fake
2,Himself church myself carry.,them identify forward present success risk sev...,2022-09-01,CNN,Julia Robinson,Business,fake
3,You unit its should.,phone which item yard Republican safe where po...,2023-02-07,Reuters,Mr. David Foster DDS,Science,fake
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,2023-04-03,CNN,Austin Walker,Technology,fake

In [35]:
df.isnull().sum()

title          0
text           0
date           0
source      1000
author      1000
category       0
label          0
dtype: int64

In [36]:
df['text'] = df['text'].str.lower()
df['title'] = df['title'].str.lower()

In [37]:
import re

def clean_text(text):
    text = re.sub(r'http\S+', '', text)  
    text = re.sub(r'[^a-zA-Z\s]', '', text)  
    return text

df['text'] = df['text'].apply(clean_text)

In [38]:
df['tokens'] = df['text'].apply(lambda x: x.split())

In [39]:
%pip install nltk

Requirement already satisfied: nltk in c:\users\mybook hype amd\appdata\local\programs\python\python313\lib\site-packages (3.9.4)
Requirement already satisfied: click in c:\users\mybook hype amd\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\mybook hype amd\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\mybook hype amd\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2026.4.4)
Requirement already satisfied: tqdm in c:\users\mybook hype amd\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\mybook hype amd\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [40]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(lambda x: [word for word in x if word not in stop_words])

[nltk_data] Downloading package stopwords to C:\Users\MyBook Hype
[nltk_data]     AMD\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [41]:
df['clean_text'] = df['tokens'].apply(lambda x: ' '.join(x))

In [42]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

df['tokens'] = df['tokens'].apply(lambda x: [ps.stem(word) for word in x])

In [43]:
df.head(1)

,title,text,date,source,author,category,label,tokens,clean_text
0,foreign democrat final.,more tax development both store agreement lawy...,2023-03-10,NY Times,Paula George,Politics,real,"[tax, develop, store, agreement, lawyer, hear,...",tax development store agreement lawyer hear ou...

In [44]:
df['text'].iloc[0]

'more tax development both store agreement lawyer hear outside continue reach difference yeah figure your power fear identify there protect security great national nothing fast story why late nearly bit cost tough since question to power almost future young conference behind ahead building teach million box receive mrs risk benefit month compare environment class imagine you vote community reason set once idea him answer many how purpose deep training game own true language garden of partner result face military discover discover data glass bed maintain test way development across top culture glass yes decision hope necessary as trade organization talk debate peace stay community development six wide write itself several fight teach billion for common fear we personal church establish store kind hundred debate hotel cut sister audience sound case that stay within information trouble be debate great themselves responsibility force people hundred bar miss others sometimes build room interesting however charge what especially north no especially us travel industry about including face ten behind black series place age soldier early trouble middle would along case what money significant sound song reason poor free want thank cultural range shoulder rest movie political fear hear past leader up edge professor determine law act change middle prove say notice travel open director argue economic seven game matter season'

In [45]:
df[['text', 'tokens']].iloc[0]

text      more tax development both store agreement lawy...
tokens    [tax, develop, store, agreement, lawyer, hear,...
Name: 0, dtype: object

In [47]:
df['tokens'].iloc[0]

['tax',
 'develop',
 'store',
 'agreement',
 'lawyer',
 'hear',
 'outsid',
 'continu',
 'reach',
 'differ',
 'yeah',
 'figur',
 'power',
 'fear',
 'identifi',
 'protect',
 'secur',
 'great',
 'nation',
 'noth',
 'fast',
 'stori',
 'late',
 'nearli',
 'bit',
 'cost',
 'tough',
 'sinc',
 'question',
 'power',
 'almost',
 'futur',
 'young',
 'confer',
 'behind',
 'ahead',
 'build',
 'teach',
 'million',
 'box',
 'receiv',
 'mr',
 'risk',
 'benefit',
 'month',
 'compar',
 'environ',
 'class',
 'imagin',
 'vote',
 'commun',
 'reason',
 'set',
 'idea',
 'answer',
 'mani',
 'purpos',
 'deep',
 'train',
 'game',
 'true',
 'languag',
 'garden',
 'partner',
 'result',
 'face',
 'militari',
 'discov',
 'discov',
 'data',
 'glass',
 'bed',
 'maintain',
 'test',
 'way',
 'develop',
 'across',
 'top',
 'cultur',
 'glass',
 'ye',
 'decis',
 'hope',
 'necessari',
 'trade',
 'organ',
 'talk',
 'debat',
 'peac',
 'stay',
 'commun',
 'develop',
 'six',
 'wide',
 'write',
 'sever',
 'fight',
 'teach',
 'billion',
 'common',
 'fear',
 'person',
 'church',
 'establish',
 'store',
 'kind',
 'hundr',
 'debat',
 'hotel',
 'cut',
 'sister',
 'audienc',
 'sound',
 'case',
 'stay',
 'within',
 'inform',
 'troubl',
 'debat',
 'great',
 'respons',
 'forc',
 'peopl',
 'hundr',
 'bar',
 'miss',
 'other',
 'sometim',
 'build',
 'room',
 'interest',
 'howev',
 'charg',
 'especi',
 'north',
 'especi',
 'us',
 'travel',
 'industri',
 'includ',
 'face',
 'ten',
 'behind',
 'black',
 'seri',
 'place',
 'age',
 'soldier',
 'earli',
 'troubl',
 'middl',
 'would',
 'along',
 'case',
 'money',
 'signific',
 'sound',
 'song',
 'reason',
 'poor',
 'free',
 'want',
 'thank',
 'cultur',
 'rang',
 'shoulder',
 'rest',
 'movi',
 'polit',
 'fear',
 'hear',
 'past',
 'leader',
 'edg',
 'professor',
 'determin',
 'law',
 'act',
 'chang',
 'middl',
 'prove',
 'say',
 'notic',
 'travel',
 'open',
 'director',
 'argu',
 'econom',
 'seven',
 'game',
 'matter',
 'season']

In [48]:
df['text'].head()

0    more tax development both store agreement lawy...
1    probably guess western behind likely next inve...
2    them identify forward present success risk sev...
3    phone which item yard republican safe where po...
4    wonder myself fact difficult course forget exa...
Name: text, dtype: object

In [65]:
df['clean_text'].apply(lambda x: len(x.split())).describe()

count    20000.000000
mean       223.949650
std         26.486955
min        167.000000
25%        201.000000
50%        224.000000
75%        246.000000
max        283.000000
Name: clean_text, dtype: float64

In [66]:
df['text'].apply(lambda x: len(x.split())).describe()

count    20000.000000
mean       250.183300
std         29.079644
min        200.000000
25%        225.000000
50%        250.000000
75%        275.000000
max        300.000000
Name: text, dtype: float64

In [57]:
df['label'].value_counts()

label
fake    10056
real     9944
Name: count, dtype: int64

In [58]:
df['clean_text'].sample(5)

12957    remain bank plan early less third entire let r...
12590    never service north certain necessary never si...
548      point child table usually simply moment go pay...
8935     bill research number either throw despite stra...
14277    value artist interview bit amount reduce speak...
Name: clean_text, dtype: object

In [59]:
df[df['clean_text'].apply(lambda x: len(x.split()) < 3)]

Empty DataFrame
Columns: [title, text, date, source, author, category, label, tokens, clean_text]
Index: []

In [60]:
df[df['clean_text'] == '']

Empty DataFrame
Columns: [title, text, date, source, author, category, label, tokens, clean_text]
Index: []

In [ ]:
# cek kata paling banyak()

from collections import Counter

all_words = ' '.join(df['clean_text']).split()
Counter(all_words).most_common(20)

[('else', 5369),
 ('listen', 5341),
 ('purpose', 5339),
 ('wear', 5338),
 ('summer', 5323),
 ('thought', 5320),
 ('child', 5314),
 ('direction', 5312),
 ('factor', 5311),
 ('ability', 5311),
 ('get', 5310),
 ('wide', 5308),
 ('relate', 5306),
 ('size', 5305),
 ('member', 5305),
 ('produce', 5304),
 ('lose', 5304),
 ('bar', 5295),
 ('leave', 5295),
 ('look', 5290)]